# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bcdb50c22946968c8a62f870f0133556d6d8e70963098ab8b2870acf17c50e0e1cea8fe2d325799686f42494b5f2df653cb178e173ede3fc0384e48fb3e3610

test:
  secret_key_base: c23ee0263cf467473379dd6fae9831c3f1e7539ce4883c47b243fe2856ea85bb60e72bb950e99986c17848652c89fcee33b6718c3fb593ec6b84fe52ddbc8914

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
